version: '3'

# See for variables description: https://hub.docker.com/_/postgres/
services:
  postgresql:
    image: postgres:latest
    container_name: ${CONTAINER_NAME}
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - postgres
    volumes:
      - ${DATABASE_PATH}:/var/lib/postgres/data
      - ${LOGS_PATH}:/logs
      - ${XMLDOCS_PATH}:/xmldocs
      - ./scripts/:/scripts/

networks:
  postgres:
    name: ${PROJECT_NAME}.Postgres
